webtalk_init -webtalk_dir E:\\MucOS\\MucOS.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-06-26 23:40:15" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ut7prbqk5rfn7v6mvouht2b8s2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.482 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1624720506092" -context "sdk\\\\bsp/1624720506092"
webtalk_add_data -client sdk -key hwid -value "1624716447730" -context "sdk\\\\bsp/1624720506092"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\bsp/1624720506092"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osiii" -context "sdk\\\\bsp/1624720506092"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1624720506092"
webtalk_add_data -client sdk -key uid -value "1624720518244" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key hwid -value "1624716447730" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key bspid -value "1624720506092" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key os -value "ucos" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key apptemplate -value "helloworld_osiii" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key projSize -value "123.3046875" -context "sdk\\\\application/1624720518244"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1624722015743"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1624722015743"
webtalk_transmit -clientid 2302286770 -regid "" -xml E:\\MucOS\\MucOS.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\MucOS\\MucOS.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\MucOS\\MucOS.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
