
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = ucos
 PARAMETER OS_VER = 1.45
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER MB_KERNEL_TICK_SRC = axi_timer_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.9
 PARAMETER HW_INSTANCE = microblaze_0
 PARAMETER compiler_flags =  -mlittle-endian -mxl-soft-mul -mcpu=v11.0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.9
 PARAMETER HW_INSTANCE = axi_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = axi_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 4.5
 PARAMETER HW_INSTANCE = axi_timer_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ucos_axiuartlite
 PARAMETER DRIVER_VER = 1.45
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = ucos_osiii
 PARAMETER LIBRARY_VER = 1.45
 PARAMETER PROC_INSTANCE = microblaze_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = ucos_common
 PARAMETER LIBRARY_VER = 1.45
 PARAMETER PROC_INSTANCE = microblaze_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = ucos_standalone
 PARAMETER LIBRARY_VER = 1.45
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


