# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/MucOS/MucOS.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3.xci
# IP: The module: 'design_1_ilmb_bram_if_cntlr_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MucOS/MucOS.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_bram_if_cntlr_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/MucOS/MucOS.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3.xci
# IP: The module: 'design_1_ilmb_bram_if_cntlr_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/MucOS/MucOS.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ilmb_bram_if_cntlr_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
